services:
  - type: web
    name: library-management-system
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/Library_Management-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
